# golangci-lint configuration for caddy-dynamic-routing
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    # exportloopref is deprecated since Go 1.22 (loopvar); keep copyloopvar instead.
    - goconst
    - gocritic
    - gocyclo
    # gofmt/goimports are configured under `formatters` for golangci-lint v2.
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for this project

    gocyclo:
      # UnmarshalCaddyfile parsers are intentionally imperative; keep this threshold practical.
      min-complexity: 35

    goconst:
      # Avoid creating constants for short/common literals.
      min-len: 3
      min-occurrences: 5

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code

    gosec:
      excludes:
        - G104  # Unhandled errors (too noisy)
        - G304  # File path provided as taint input (expected for config files)

    dupl:
      threshold: 150

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst

      # Exclude known false positives
      - path: datasource/
        text: "G402:"  # TLS InsecureSkipVerify is configurable
        linters:
          - gosec

      # Package name is intentionally 'http' to match directory.
      - path: datasource/http/
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/puxu-msft/caddy-dynamic-routing

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
